/**
 * This class is generated by jOOQ
 */
package com.pretech.jooq;


import com.pretech.jooq.tables.Employee;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table test.employee
	 */
	public static final Employee EMPLOYEE = com.pretech.jooq.tables.Employee.EMPLOYEE;
}
